- sample_files/.travis.yml
- Unit tests test dependencies, so no there's no point in running twice.
- Make 8.0 the default in the sample files.
> Update sample files

- sample_files/.travis.yml
The version variable in the link check case is necessary because getting dependencies errors out otherwise
> [IMP] only take a shallow copy of branches we need, add VERSION to lint

- travis/requirements.txt
The new werkzeug series 0.10 released on 2015-01-29 break the API compatibility, we should stay on 0.9 series as it already crash on tests: https://travis-ci.org/petrus-v/server-tools/jobs/49292789
```
2015-02-03 09:42:28,065 23608 INFO openerp_test openerp.service.server: Initiating shutdown
2015-02-03 09:42:28,065 23608 INFO openerp_test openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
Traceback (most recent call last):
File "/home/travis/odoo-8.0/openerp-server", line 5, in <module>
openerp.cli.main()
File "/home/travis/odoo-8.0/openerp/cli/__init__.py", line 71, in main
o.run(args)
File "/home/travis/odoo-8.0/openerp/cli/server.py", line 174, in run
main(args)
File "/home/travis/odoo-8.0/openerp/cli/server.py", line 168, in main
rc = …
```
> Pin werkzeug on stable 0.9 versions

- travis/test_server
When the tests are launched, the modules to test are already installed. Therefore we should avoid to reinstall the modules to run the tests. (it's already the case with unittest=1)This will prevent some errors with xml data defiend with noupdate="1".  (https://travis-ci.org/OCA/l10n-belgium/jobs/54770816, https://github.com/acsone/l10n-belgium/blob/8.0-add-account_bank_statement_import_coda/account_bank_statement_import_coda/demo/demo_data.xml)
> [FIX] Tests should be performed in update mode

- .travis.yml
- README.md
- sample_files/.travis.yml
- sample_files/oca_dependencies.txt
- tests/test_repo/oca_dependencies.txt
- travis/clone_oca_dependencies
- travis/travis_install_nightly
use repo/oca_dependencies.txt rather than an explicit list of checkouts in
.travis.yml
closes #105
> cross repository dependency management

- git/README.md
- git/cfg
- git/pre-commit
Script for making the same tests as in Travis before committing
===============================================================
This script allows to make a test before each commit you make on your local
git repository, checking same things as in Travis PYLINT_CHECK phase of
OCA maintainer quality tools.
For using it, you can make two options:
1. Copy files to local git repository into .git/hooks, and you will enable the
checks for that git repository.
2. Copy files to git template directory. In Ubuntu, it's located in
/usr/share/git-core/templates/hooks/
Then, making `git init`  inside a git repository, these files will be copied,
and you will have these checks available for it.
> [IMP] Added git pre-commit script hook for checking flake8 and pylint

- tests/test_repo/oca_dependencies.txt
- tests/test_repo/test_module/__openerp__.py
This makes test fail for previous versions (7.0, 6.1)
Fixes #173
> Remove pinned 8.0 test dependency

- sample_files/.travis.yml
- travis/travis_after_tests_success
- travis/travis_run_tests
Currently, the `coveralls` command runs on every build: the tests builds but the lint one as well.
Yesterday, I added a new build on OCA/connector#60 which builds the documentation; I added environment variables to switch off `coveralls` (https://github.com/OCA/connector/commit/bc55f9aab88927a75624778fd02922ab426264e6#diff-354f30a63fb0907d4ad57269548329e3R15).
After a few exchanges on Twitter with @bwrsandman and @pedrobaeza, I engaged myself to propose a change in the MQT to allow `coveralls` to run conditionnally. So here it is.
This PR is backward compatible. To be effective on the projects, we'll need to replace `coveralls` by `travis_after_tests_success` in all the `.travis.yml` files. If we agree on this change, I can make a script that creates pull requests for that (and in any …
> Run coveralls conditionally

- sample_files/.travis.yml
- travis/travis_transifex.py
Following @pedrobaeza's [suggestion](https://github.com/OCA/maintainer-quality-tools/issues/194#issuecomment-104869668), two more options to transifex creation have been adeed.
These can be overridden in the `.travis.yml` environment section.
* `TRANSIFEX_FILL_UP_RESOURCES`, default ~~False~~ True, activates TM at creation
* `TRANSIFEX_TEAM`, default [23907](https://www.transifex.com/organization/oca/team/23907/), joins the OCA team at creation instead of creating another
~~The default for `TRANSIFEX_FILL_UP_RESOURCES` is up for debate, I will change it to True if enough people want it. Personally I would rather not have auto fill of terms to 100% if they're done automatically.~~
> Transifex create options

- sample_files/README.md
SVG badge matches the styles of other README badges such as build status
See the difference here for example: https://github.com/OCA/vertical-isp/commit/c6a40aa4cdb9808ecde0e8d6fa3208a13016efdb?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
PNG: [![Coverage Status](https://coveralls.io/repos/OCA/vertical-isp/badge.png?branch=7.0)](https://coveralls.io/r/OCA/vertical-isp?branch=7.0)
SVG: [![Coverage Status](https://coveralls.io/repos/OCA/vertical-isp/badge.svg?branch=7.0)](https://coveralls.io/r/OCA/vertical-isp?branch=7.0)
Build Status: [![Build Status](https://travis-ci.org/OCA/vertical-isp.svg?branch=7.0)](https://travis-ci.org/OCA/vertical-isp)
> Use svg badge for coveralls

- sample_files/README.md
The REPO_ID and REPO_NAME is available in the runbot url (evg : https://runbot.odoo-community.org/runbot/repo/github-com-oca-REPO_NAME-REPO_ID)
> Add runbot badge

- .travis.yml
- sample_files/.travis.yml
This should speed up the container based builds by taking time out of the pip install command and using ready-made containers which add virtually no time.
These packages were not taken out of travis/requirements.txt for backwards compatibility. The speedup should still be there since in those cases, pip will see the dependency installed and not attempt to install them.
> Add python libs to container directives

- travis/cfg/travis_run_pylint.cfg
More info here:
https://github.com/OCA/maintainer-quality-tools/issues/112
We need enable 
W0402(deprecated-module) to detect conf
+[IMPORTS]
+deprecated-modules=pdb,pudb
But show fail only if module is installed.
And we need enable 
F0401(import-error)
If you try use deprecated modules without install depends.
And now "import openerp" show a import-error then I add odoo directory to PYTHONPATH to detect this import.
> [IMP][pylint-conf] Add deprecated modules: pdb, pudb. And enable fails W0402 to check it #112

- travis/travis_install_nightly
this fixes my install bugs for odoo + .NET build with mono, on 1 system
e.g. see [here](https://travis-ci.org/mathi123/dotnet/builds/68430398)
> [IMP] pip --user argument to make travis .NET build work

- .travis.yml
- sample_files/.travis.yml
python-yaml is now enabled in container builds
https://github.com/travis-ci/travis-ci/issues/3911
> Add python-yaml to container directives

- travis/test_server.py
With docker I had a error of `command not found` my last print: `coverage run...`
```python
coverage run /root/odoo-8.0/openerp-server -d openerp_test --stop-after-init --log-level info --addons-path /root/myproject/lodigroup,/root/odoo-mexico-v2,/root/addons-vauxoo,/root/odoo-afr,/root/account-financial-tools,/root/odoo-ifrs,/root/server-tools,/root/odoo-8.0/addons --log-handler openerp.tools.yaml_import:DEBUG --test-enable --update lodi
Traceback (most recent call last):
File "/root/maintainer-quality-tools/travis/test_server", line 278, in <module>
exit(main())
File "/root/maintainer-quality-tools/travis/test_server", line 239, in main
stdout=subprocess.PIPE)
File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line …
```
> [REF] test_server: Print full command executed

- travis/travis_run_tests
fix #213: no tests only with explicit LINT_CHECK
We are trying to handle many different situations here:
- a .travis.yml that always sets variables to 0 or 1, like the one in
samples/.travis.yml (4 cases)
- a line that has no options at all (it should lint, then test)
- a line that has only LINT_CHECK=1 (special case: it should not run
tests)
- a line that has only LINT_CHECK=0 (special case: it should only run
tests)
That makes a total of 7 cases that should all be handled here.
See #213 for a discussion on how to make all that more explicit (will
require an update in all .travis.yml files).
> fix #213: handle all lint/test cases, refactor

- .travis.yml
- tests/test_repo/second_module/__openerp__.py
- travis/self_tests
- travis/test_server.py
Currently the database setup phase install all modules, and tests are run with a second command, using an upgrade.
This has a couple of issues:
* In some cases tests during an upgrade have different results from tests during and install.
* Init hooks don't run during an upgrade and their code is reported as not being covered by tests.
This PR changes the tests, so that only the core an external module dependencies are preinstalled in the setup phase, so the repo module tests can be executed with a `--init` instead of `--update`.
> Preinstall dependencies and run tests with --init instead of --upgrade

- .coveragerc
- .travis.yml
- README.md
- travis/getaddons.py
- travis/self_tests
- travis/test_server.py
- travis/travis_run_tests
The point in #35 is no longer the case since most tests are python.
Improve coverage of getaddons.py and bring overall coverage to about 90%
> Reactivate python coverage on MQT itself

- travis/getaddons.py
- travis/test_server.py
When finding dependencies, search for modules in all addon paths - this is necessary for OCB travis tests, cf https://github.com/OCA/OCB/pull/287#issuecomment-125867121
> [IMP] search all addon paths for the modules to test

- travis/travis_transifex.py
The bug was due to the recent changes in the `setup_server` function.
If we don't set anything in `preinstalled_modules`, only `base` is installed. So the modules to translate aren't installed and the script cannot export their `.pot` file.
> [FIX] Fix transifex export bug due to modules not installed

- travis/run_pylint.py
- travis/self_tests
- travis/test_pylint
This fix is to avoid next issue:
https://github.com/OCA/runbot-addons/pull/53
> [FIX] test_pylint: Fix empty paths

- travis/cfg/travis_run_pylint.cfg
* Numbers2name
Many times we need to check the pylint official documentation to get pylint-number information.
But if we use the message-short-name is easiest identify it.
By example:
- `duplicated-key` is more explicit that `W0109`
* Multi-lines
- To reduce conflicts of use same line if add new or remove old checks.
- To identify a PR diff easiest.
> [REF] pylint: Change number of message by name of message and add multiline

- travis/test_pylint
Change from this
to this
And add red message in error case.
> [REF] test_pylint: Show warning of empty paths but no error. Add colors to pylint global result.

- .travis.yml
- travis/cfg/travis_run_pylint_pr.cfg
- travis/getaddons.py
- travis/git_run.py
- travis/run_pylint.py
- travis/self_tests
- travis/test_pylint
Currently, we have a problem that if we add a new conventions in pylint-test-1 we will have all repos red in travis builds for stable branches and PR ones.
But currently we are working with next steps:
1. We have created a new pr to oca/PROJECT-X branch 8.0
2. We received feedabck from reviewers:
3. Please, rename the class to `CamelCase`
4. Please, add OCA author.
5. Please, change your comment `encondig` by `coding`
6. Other ones.
If we can automate it, Why not automate it?
Save time of reviewer, save time of developers just in new changes.
Then we need a middle step to add new conventions without have all repos red.
We can change the modules progressively of new conventions.
This feature run with original
`pylint pylint.cfg all_modules`
plus run other one with new conventions in just …
> [IMP] run_pylint: Add feature to check new conventions just in modules changed.

- tests/test_repo/broken_lint/__init__.py
- tests/test_repo/broken_lint/case_fields.py
- travis/cfg/travis_run_pylint_pr.cfg
[example](https://github.com/OCA/sale-workflow/pull/213#discussion_r39856737)
Result of this PR:
```log
************* Module broken_lint.case_fields
broken_lint/case_fields.py:10: [W8103(translation-field), MyExampleField] Translation method _("string") in fields is not necessary.
broken_lint/case_fields.py:11: [W8103(translation-field), MyExampleField] Translation method _("string") in fields is not necessary.
broken_lint/case_fields.py:18: [W8103(translation-field), MyExampleField2] Translation method _("string") in fields is not necessary.
broken_lint/case_fields.py:19: [W8103(translation-field), MyExampleField2] Translation method _("string") in fields is not necessary.
```
> [IMP] pylint: Enable check to verify fields with _('string')

- .travis.yml
- travis/travis_after_tests_success
If coveralls.io [fails](https://github.com/OCA/maintainer-quality-tools/issues/247)
we have a emergency option: show a small report in log output.
Example
> [REF] after_success: Show coverage report

- travis/cfg/travis_run_pylint_pr.cfg
- travis/travis_install_nightly
We have next [guideline](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#idioms):
`If a function is too long or too indented due to loops, this is a sign that it needs to be refactored into smaller functions`
The unit of measure of [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) can to help us to check it
Before of enable this check I need to know if is a good idea for you.
> [IMP] pylint: Enable check of cyclomatic complexity

- .travis.yml
- tests/test_repo/broken_lint/__openerp__.py
- tests/test_repo/broken_uninstallable/I0013.py
- tests/test_repo/broken_uninstallable/README.rst
- tests/test_repo/broken_uninstallable/__init__.py
- tests/test_repo/broken_uninstallable/__openerp__.py
- tests/test_repo/broken_uninstallable/doc/index.rst
- tests/test_repo/broken_uninstallable/interpreter_wox.py
- tests/test_repo/broken_uninstallable/model.py
- tests/test_repo/broken_uninstallable/model_view.xml
- tests/test_repo/broken_uninstallable/test.yml
- tests/test_repo/broken_uninstallable/tests/__init__.py
- tests/test_repo/broken_uninstallable/tests/dummy_test.py
- travis/getaddons.py
- travis/run_pylint.py
- travis/test_server.py
The following commands need to be adapted to ignore uninstallable modules
Later:
* coverage (it seems `__unported__` is not excluded from coverage at the moment, so this can be left for another PR)
* code climate (we just have a sample file, so this can be left for a future improvement)
> [FIX] let travis tools ignore uninstallable modules

- .travis.yml
- sample_files/.travis.yml
Currently we have a error in cache result
[could not download cache](https://travis-ci.org/OCA/maintainer-quality-tools/jobs/81485157#L136)
[Store cache - empty file](https://travis-ci.org/OCA/maintainer-quality-tools/jobs/81485157#L281)
With this PR we will have in `store cache` next output:
```bash
store build cache
3.54schange detected:
/home/travis/.cache/pip/http/0/8/c/d/4/08cd447a8124a068fe40c29b184ad1eca9cda6eff048ab59ffbaab5e
/home/travis/.cache/pip/http/0/c/7/8/c/0c78cc5ddccddcf3238359feeac7e1cddd59216d6ded4659cf5965cd
/home/travis/.cache/pip/http/0/e/5/0/b/0e50bf69d3ad563fafdaccae0f81317c29bda91e335305bd70fbb8e3
/home/travis/.cache/pip/http/0/e/7/b/9/0e7b99547a0247a24df2175f35e166cf96f0194417e99b4851dbf306
/home/travis/.cache/pip/http/0/e/b/8/e/0eb8e3da6d73f4de2940eb7f94eb65bff81 …
```
> [REF] .travis.yml: Fix caching of travis-ci

- .travis.yml
- travis/cfg/travis_run_pylint.cfg
- travis/cfg/travis_run_pylint_beta.cfg
Disable error [W0402(deprecated-module), ] Uses of a deprecated module 'openerp.osv'
Now show warning beta message
This PR fix the thread "Maintainer-quality-tools multiple quick changes" sent to contributors email.
> [REF] pylint_beta.cfg: Add deprecated module in beta messages

- .travis.yml
- travis/self_tests
- travis/test_pylint
- travis/travis_install_nightly
- Use new pylint_odoo package fix OCA/maintainer-quality-tools#268
- Install `pylint_odoo` packages only is necessary.
> [REF] pylint_run: Use of pylint_odoo instead of deprecated pylint_oca

- travis/clone_oca_dependencies
- travis/test_server.py
- travis/travis_install_nightly
- travis/travis_transifex.py
Instead of $HOME because other tools that expect to have a directory which
contains only valid addons paths will get confused if other directories are
created in $HOME (e.g. npm creates a 'node_modules' folder).
Follows discussion on #288
> Store dependency repositories in $HOME/dependencies

- travis/getaddons.py
It allows a build to continue if a build did not create the
'$HOME/dependencies' folder beforehand.
Fixes #293
> Do not include inexistent addons path

- travis/travis_install_nightly
`npm install less less-plugin-clean-css` creates a `node_modules` folder in the addons path.
It makes builds that expect to only find addons in the addons path to fail.
Example:
https://travis-ci.org/OCA/connector/jobs/89892364
Using `npm install -g` makes the installation of node modules global so it doesn't pollute the addons path.
Tested on: https://github.com/OCA/connector/pull/146
> Install node packages globally

- .travis.yml
- travis/self_tests
- travis/test_server.py
- Useful and fully tested in next runbot-docker https://github.com/OCA/runbot-addons/pull/71
- Useful to use travis2docker locally and runbot-travis2docker with OCA repositories
- [REF] .travis.yml: Using cp instead mv to avoid docker/docker#4570
Maybe, this change will can be useful with other CI that use docker to build:
- [codeship will be use docker](http://pages.codeship.com/webinars/getting-started-with-continuous-delivery-using-docker?utm_campaign=Weekly+Newsletters&utm_source=hs_email&utm_medium=email&utm_content=24008076&_hsenc=p2ANqtz-8m3QJNm6Hk560x3IwMJk94m9oLIiyB7lJNKuIEBpYJQXqajwDdLPQaBW3vj6kqWrZz1qndrnBbyYAlweFdiLxcX_rxlQ&_hsmi=24008076)
- [shippable use docker](http://docs.shippable.com/)
> [IMP] test_server: Enable store database (avoid delete it) and allow run a instance alive

- travis/test_server.py
- Create server configuration file
Usefully when you want start server manually without set --addons-path
- Copy attachment from database template
- Fix https://github.com/OCA/maintainer-quality-tools/issues/299
> [REF] test_server.py: Create server configuration file and copy attachment

- travis/test_server.py
- The change presented here comes from #249 where preinstalled modules in testing instance are getting some of the modules to be unit tested. So, in some cases may lead to errors like are currently happening in 8.0 branch for OCA/rma
For example there is [travis#103328194](https://travis-ci.org/OCA/rma/jobs/103328194):
Where the module **`crm_rma_lot_mass_return`** appears in both lists:
```bash
Modules to test: crm_claim_product_supplier,crm_claim_rma,crm_claim_rma_code,
crm_rma_advance_warranty,crm_rma_claim_make_claim,crm_rma_location,
crm_rma_lot_mass_return,crm_rma_prodlot_invoice,crm_rma_prodlot_supplier,
crm_rma_stock_location,product_warranty
```
```bash
Modules to preinstall: ['product_unique_serial', 'crm_rma_lot_mass_return', 
'purchase', 'crm_claim_type', 'product', 'sale', …
```
> [FIX] Apply patch taken from OCA/maintainer-quality-tools#249

- travis/test_server.py
This is required e.g. for OCA/server-tools: travis config generates a
server configuration file, which is required by the server_environment
module. f4d9198 would overwrite that file causing build failures.
> don't overwrite existing server config

- travis/clone_oca_dependencies
- If main project and/or projects depends exists a `requirements.txt` then will be used to install.
- `pip install -r requirements.txt`
- Allow install depends recursively between projects.
- Allow use a global standard to install python dependencies.
> [IMP] clone_oca_dependencies: pip install requirements.txt

- travis/test_pylint
Using the "PYLINT_CONFIG_FILE" environment variable,
it's possible to choose which config file will be used
during the regular lint check (i.e. not for Pull Request use case).
> Add env variable to set default pylint config file

- travis/test_server.py
- Allow get a live output to know the current status
- Allow to know a unusual large step without wait the full timeout of the build
- e.g. A accidental `pdb` or `raw_input`
- Avoid the travis error of [Build-times-out-because-no-output-was-received](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received)
- Avoid use `travis_wait` script.
Example of enabled live output [video](https://youtu.be/fG1LIG4prTs)
> [REF] test_server: Enable live output and fix Build-times-out-because-no-output-was-received

- travis/test_server.py
- We added output to `openerp_template` but this section is without color when you use `travis_wait`.
- Add the same coloured like as `openerp_test` script.
> [REF] output log: Add coloured log in `openerp_template` section too when use `travis_wait` script

- travis/cfg/travis_run_pylint_pr.cfg
Reverts OCA/maintainer-quality-tools#298
Opened discuss from @lepistone comment:
https://github.com/OCA/maintainer-quality-tools/pull/298#issuecomment-176651653
>Sorry I came late to the party, but I :-1: the `images` check (so I :+1: @StefanRijnhart "can we revert this").
For me "warning" means something is wrong, but for some reason it doesn't crash the program (or the build or whatever). It is still something you want to get rid of. So in general I think we shouldn't add warnings unless we think they should be enforced one day.
In that case I have the impression it is not always relevant, especially if it is a random screenshot (much less important than documentation, for example).
> Revert "[IMP] Add images to required keys of manifest file"

- .travis.yml
- tests/test_repo/broken_module/I0013.py
- travis/cfg/travis_run_pylint.cfg
Pylint allows you to ignore a file completely adding a "# pylint: disable-all"
line at the top. This is especially useful in cases where a file is
copied for some reason and we don't want to mess too much with it to
avoid diverging from the original. This option make the "disable-all"
option an error, rather confusingly.
> allow to ignore a file

- travis/travis_install_nightly
- Avoid continue to run of the build when exists a error in `clone_oca_depedencies` script.
> [REF] travis_install_nightly: Exit if clone_oca_depedencies script returned different to zero

- travis/clone_oca_dependencies
- If you run 2 times the `clone_oca_dependencies` script you will get:
- First time: `git clone ...`
- Second time: `git pull ...` 
- Update repositories dependencies previously downloaded.
- Useful when you use MQT locally to upgrade repositories
> [REF] clone_oca_dependencies: Add feature to upgrade git version of repositories dependencie

- travis/travis_run_tests
Closes https://github.com/OCA/maintainer-quality-tools/issues/339 and https://github.com/OCA/maintainer-quality-tools/issues/334
If you want help the travis request
https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix
`Please take into account that Travis CI is an open source service and we rely on worker boxes provided by the community. So please only specify as big a matrix as you actually need.`
You could apply the following change in your own fork:
```patch
===.travis.yml
-   - TRANSIFEX="1"
+   # - TRANSIFEX="1"
```
But if you want let your fork repository without changes with this PR won't see a false red.
FYI this change is compatible with other not oca projects using OCA/MQT with `TRANSIFEX_USER="not_oca_user@mycompany.com"` to manage translations.
FYI I'm using …
> [REF] travis_run_tests: Avoid false red from forks for transifex builds

- README.md
- travis/test_server.py
- travis/travis_after_tests_success
- Use  `TEST_ENABLE=0` if you want run a odoo instance without parameter `--test-enable` to avoid run tests
- This parameter is useful for runbot based on MQT scripts where we don't like run tests
> [REF] test_server: Add test-enable optional

- travis/travis_after_tests_success
- travis/travis_install_nightly
Coveralls.io is failing too much recently.
I good example is this PR (I don't have changes affecting by monitored py files):
Codecov adds an additional and useful github statuses to split a average of coverage just of your diff.
- Codecov have integrate [browser plugins](https://github.com/codecov/browser-extension)
> [ADD] Enable codecov: Show a extra github statuses focused for just changes

- cfg/.coveragerc
This PR adds `NotImplementedError` to ignores in `.coveragerc` - which is generating what I consider to be false positives in some modules. Seems a bit redundant to be testing something that is clearly not implemented IMO
> [IMP] coveragerc: Ignore NotImplementedError

- .travis.yml
- The new version of [pylint-odoo](https://github.com/OCA/pylint-odoo/pull/69) detects a re-import with `alias import`, then the expected errors should be increased because we have imported 3 times the `Warning` library
> [REF] .travis.yml: Update PYLINT_EXPECTED_ERRORS to new version of pylint

- travis/test_server.py
This PR adds additional server_options flag in order to allow the ability to pass additional options to the server init, outside of the standard Travis options.
This is required in order to allow Runbot-Travis2Docker to pass the necessary [`--log-db`](https://github.com/odoo/odoo-extra/blob/master/runbot/runbot.py#L897) command to the underlying server. Using the pre-existing options would allow for overwrite via the Travis file, which is undesired.
* Add `SERVER_OPTIONS` env var
* Append server_options to relevant build commands
> [ADD] travis: Add server_options

- travis/travis_install_nightly
If exists a caching git directory with odoo we can re-use it just for update last changes faster after last cached date.
- Useful for [runbot dockerized based on MQT](https://github.com/OCA/runbot-addons/tree/9.0/runbot_travis2docker)
- Useful for [travis caching](https://docs.travis-ci.com/user/caching/)
Example where works
- Runbot build: http://runbot.vauxoo.com/runbot/repo/git-github-com-vauxoo-crm-git-35
- Log: http://runbot.vauxoo.com/runbot/static/build/17286-8-0-2ca7ea/logs/job_10_test_base.txt
> [REF] travis_install_nightly: Installing odoo from cache (if exists)

- .travis.yml
- travis/test_pylint
Second part of https://github.com/OCA/pylint-odoo/pull/77
Full fix https://github.com/OCA/maintainer-quality-tools/issues/366
> [REF] test_pylint: Use valid_odoo_versions from version environment variable

- travis/travis_after_tests_success
* Guard coverage calls to fail gracefully - both libraries output the error via logging, we don’t want to exit
Without this if coveralls fails due to no project existing, CodeCov will not be attempted. This means that BOTH Coveralls and CodeCov accounts are required to output coverage only via CodeCov.
I went ahead and guarded both though, because I didn't see any reason why not.
> [FIX] Graceful coverage failures

- travis/travis_install_nightly
Currently runbot show the following [log](https://runbot2.odoo-community.org/runbot/static/build/3272576-8-0-ee406d/logs/job_20_test_all.txt)
```bash
...
Creating instance:
~/OCB-8.0/openerp-server -d openerp_template --log-level=info --stop-after-init --init product,base,stock
[Errno 2] No such file or directory
+=======================================
|  Tests summary:
|---------------------------------------
| test_server.py              FAIL
+=======================================
```
MQT is not finding `~/OCB-8.0` (uppercase) path because the folder is created with lowercase
[test_server.py#L303-L304](https://github.com/OCA/maintainer-quality-tools/blob/e86286bdf325b61188ca25f1b14f8211e4f6bc89/travis/test_server.py#L303-L304) is using original name (without upper or lowercase …
> [FIX] travis_install_nightly: Fixing ODOO_PATH when is OCB (uppercase) used

- travis/getaddons.py
Without this fix, when running  pylint-odoo, I get this error of flake
```
FLAKE8_CONFIG_DIR="$(dirname $0)/cfg"
dirname $0
flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8__init__.cfg
status1=$?
flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8.cfg
./.git/hooks/getaddons.py:131:1: E305 expected 2 blank lines after class or function definition, found 1
status2=$?
TRAVIS_PULL_REQUEST="true" TRAVIS_BRANCH="HEAD" TRAVIS_BUILD_DIR=`pwd -P` $(dirname $0)/test_pylint
dirname $0
pwd -P
```
> [FIX] getaddons lint

- tests/test_repo/broken_module/test.yml
- travis/cfg/travis_run_flake8.cfg
- travis/cfg/travis_run_flake8__init__.cfg
- travis/test_server.py
- [REF] broken_module: Fix False expression, now is required a string
- [REF] flake8 rc: 'Skip F999 dictionary key 'name' repeated with different values' because pylint support this check
- [REF] test_server: Fix flake8
> [FIX] Fixes CI result

- git/pre-commit
[REF] pre-commit: when TRAVIS env var is true, skip question and run lints
Show a friendly confirmation message in order to skip easiest the lint check in each commit:
> [REF] git-hook: Ask if we want run lints

- travis/test_server.py
Previously the tested directory ought to be an addons directory.
With this change, it can instead contain several addon directories.
A search will be done inside it,to find all contained addon directories,
and test will be run on all of them.
Intended to replace #382
> Allow tested directory to contain addon dirs

- travis/requirements.txt
take a look to https://github.com/OCA/sale-workflow/pull/388
> [FIX] set pillow version in travis requirements, version 8.0 PR are failling

- .travis.yml
- README.md
- travis/test_server.py
**What I did**
_Before:_ Hard coded db names (template and actual db)
_After:_ Default to same hard coded names, if no environment variable is present.
**Why I did it**
- Having an external postgres service holding the databases,
- I want to be able to organize and reuse my build db inventory,
- in order to shorten test cycles and reuse built databases for staging instances
**I already know the questions...**
- Yes, It's easy to share filestore. I have thought of that. Eg. with docker volumes.
- Yes, there is runbot, but with those two changes, I save a lot of work by not having to setup and include another, somewhat bulky, infrastructure stack. Hey, my time is valuable, too :)
- No, it's not reinventing the wheel. There are just red and green tires available. You don't want green tires …
> [IMP] better db inventory with flexible db names

- tests/test_repo/broken_module/broken_example.js
- tests/test_repo/broken_module/broken_example2.js
- travis/travis_install_nightly
More info: https://github.com/OCA/pylint-odoo/pull/97
- Fix exit early if you want test both: `LINT_CHECK="1" TESTS="1"`
TODO:
> [REF] maintainer-quality-tools: Use eslint instead of jshint for javascript lints

- travis/cfg/travis_run_flake8.cfg
- travis/cfg/travis_run_flake8__init__.cfg
The following check is emitted:
`broken_module/__openerp__.py:3:5: F601 dictionary key 'name' repeated with different values`
Because new version of flake8 changed the name of the check from F999 to F601
See the following video with the evidence of the case:
[![IMAGE ALT TEXT](http://img.youtube.com/vi/DbfrGHpcaiw/0.jpg)](http://www.youtube.com/watch?v=DbfrGHpcaiw "Video Title")
Previously PR using F999
https://github.com/OCA/maintainer-quality-tools/pull/390
> [REF] flake8.cfg: Flake8 renamed F999 -> F601

- README.md
- cfg/.coveragerc
See https://github.com/OCA/website-cms/pull/9#pullrequestreview-22552007
@moylop260 alternatively we could consider looking up for custom `.coveragerc` in the repo. What do you think?
> Ignore *_example packages in coverage check

- sample_files/.travis.yml
- travis/travis_install_nightly
* Add PhantomJS update to circumvent [MutationObserver](https://travis-ci.org/OCA/e-commerce/jobs/213050636#L847) error in V10
We have now used this to fix tours in 3 PRs:
* https://github.com/OCA/website/pull/329
* https://github.com/OCA/e-commerce/pull/155
* https://github.com/OCA/website/pull/331
The actual install/update adds all of 10 seconds on to the build. IMO this is better than requiring a change in relevant Travis files - this error is pretty hard to spot & took me a decent amount of time to wrestle down.
I switched OCA/website#329 to use this branch in https://github.com/OCA/website/pull/329/commits/82e5e8a06b6fb21a85e9b490d3cd44fb67473f9b to provide proof of fix.
> [FIX] Update PhantomJS

- travis/test_server.py
Fix the following output
"""
Modules to test: base
'NoneType' object is not iterable
+=======================================
|  Tests summary:
|---------------------------------------
| test_server.py              FAIL
+=======================================
"""
> [FIX] test_server: Support empty preinstall modules

- travis/test_server.py
It is safer and it is how Odoo parses it.
> [FIX] use ast.literal_eval instead of eval to parse manifest

- travis/requirements.txt
- travis/travis_install_nightly
Travis show a error because can't download packages referenced to gna.org because now is closed:
Related with:
-  https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3390
- https://github.com/odoo/odoo/pull/6781
Of course, we could create a new method to get requirements.txt from odoo, but the focus of this PR is a small fix with current version.
> [FIX] install: Remove deprecated download.gna.org

- travis/travis_install_nightly
The new host server there are many network issue.
Webkit is not a package required to run the tests correctly in the major of the builds.
So we can continue if there is a issue.
> [REF] install: Skip webkit installation if there is a issue

- travis/travis_install_nightly
Our CI is failing due to https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3518. I propose that we switch to a Github mirror temporarily, then we can switch back once I get the notification on the ticket.
An alternative, which may actually be better, is to host our wkhtmltopdf inside of MQT & not deal with the remote downloads. This isn't the first time we've had issues with wkhtmltopdf installations.
> [FIX] Switch to wkhtmltopdf GitHub URI

- sample_files/.travis.yml
Sometimes it is important to install a specific wkhtmltopdf on a repo. Maintainers need to know how to properly set this up.
See https://github.com/OCA/reporting-engine/pull/144#discussion-diff-123189206R32 for an example.
> Add helper comment to install a specific wkhtmltopdf version

- travis/apis.py
This method make commit to the uncommitted changes on weblate repository
In some cases the user does not make the commit into the repository of weblate.
Because the user do not have permission or because the user does not know that it is a necessary action in the process of the translated
With this change the commit will do if necessary
Related with https://github.com/Vauxoo/maintainer-quality-tools/pull/213
> [IMP] apis.py: Adding new method _component_commit

- travis/travis_install_nightly
Travis use a virtualenv to install python packages, if we use `pip install --user ...` then it will have 2 environments with possible errors like as:
https://github.com/OCA/l10n-spain/pull/569
Before this PR:
- ![screen shot 2017-07-06 at 17 02 35](https://user-images.githubusercontent.com/6644187/27934379-0ce2c49a-626b-11e7-93d7-2b0344bf38a6.png)
After this PR:
- ![screen shot 2017-07-06 at 17 25 08](https://user-images.githubusercontent.com/6644187/27935025-383d23b2-626e-11e7-9ac2-6850b69ce07d.png)
The `--user` parameters was added https://github.com/OCA/maintainer-quality-tools/pull/209 because a error from https://github.com/OCA/dotnet/pull/6 but that environment is not using a standard python image.
They are using:
https://docs.travis-ci.com/user/languages/csharp/
And the log show …
> [REF] install: pip install w/o --user

- requirements.txt
A build failed due to unittest2 not installed:
https://travis-ci.org/OCA/connector/jobs/250791548#L647
Adding the lib in the project's local requirements.txt fixed the build:
https://github.com/OCA/connector/commit/3e8d50754252ea4fe764a79c6a7e0cdc0c4e4070
I don't know what changed, but the lib is required anyway.
> Install unittest2

- requirements.txt
Runbot has recently become broken due to `pyopenssl` compilation errors:
* https://runbot2.odoo-community.org/runbot/static/build/3298536-153-e1c46f/logs/job_20_test_all.txt
* https://runbot2.odoo-community.org/runbot/static/build/3298522-882-a8d59b/logs/job_20_test_all.txt
Current production build of server-tools was passing, but is now failing since I rebuilt:
* https://runbot.odoo-community.org/runbot/build/3298530
The traceback:
```
/home/odoo/odoo-10.0/odoo-bin -d openerp_template --log-level=info --stop-after-init --init base_search_fuzzy,website_sale,base
Traceback (most recent call last):
File "/home/odoo/odoo-10.0/odoo-bin", line 5, in <module>
__import__('pkg_resources').declare_namespace('odoo.addons')
File "/.repo_requirements/virtualenv/python2.7/local/lib/python2.7/site-packa …
```
> [FIX] Fix builds by updating pyopenssl

- sample_files/.travis.yml
- travis/travis_install_nightly
This adds a shortcut for the installation of website dependencies SASS and Compass, which has been causing some considerable issues lately. Most recent 
* https://github.com/OCA/website/pull/361#issuecomment-316003296
* https://github.com/OCA/social/pull/179#issuecomment-316238557
cc @moylop260 @Yajo
> [IMP] Add shortcut to install SASS and Compass

- travis/travis_install_nightly
Fix OCA/maintainer-quality-tools/#467
This change require use the new cache pip way to build faster:
- https://github.com/OCA/maintainer-quality-tools/pull/257
> [REF] install: Re-active pip install lxml

- travis/apis.py
- travis/travis_weblate.py
When one module is not into the list of component on weblate, that module is excluded for `travis_weblate.py`
In this pull request this mistage was fixes up.
Based on the modules installed and the components registered on weblate, if that module is installed but the same module is not present into the weblate component now the folder `i18n` and the *.po files is going to created
Only the environment variable `LANG_ALLOWED` should be setter to a default list of languages supported
Related with https://github.com/Vauxoo/maintainer-quality-tools/pull/219
> [FIX] travis_weblate.py: Create folder i18n and *.po file

- README.md
- travis/self_tests
- travis/test_server.py
- travis/travis_install_nightly
Support branches in the environment variable VERSION of .travis.yml
Now
```
VERSION=master
ODOO_REPO=odoo/odoo
```
Expected
```
VERSION=pull/3
ODOO_REPO=odoo/odoo
```
In the enviroment variable `VERSION` can be used:
Referring to issue #173
> [IMP] Support branches in the environment variable VERSION of .travis.yml 

- sample_files/.travis.yml
removed some superfluous config settings regarding wkhtmltopdf, by now we install this in `travis_install_nightly`, no apt necessary and on newer build environments (trusty), installing via apt is actually harmful because it's the wrong version but wins against the version installed by said script.
Used in https://github.com/OCA/reporting-engine/pull/141
> [IMP] clean up wkhtmltopdf configuration

- travis/apis.py
When the components it is more that 25 the API of Weblate paginated the results, then should be get each page
For more information https://docs.weblate.org/en/latest/api.html#any--
Related with https://github.com/Vauxoo/maintainer-quality-tools/pull/231
> [FIX] apis.py: Fix when the components on weblate are more 25

- tests/test_repo/broken_deprecated/__openerp__.py
- travis/apis.py
When is it used the command `git clone` over the ssh the command need a console to answer the follow question
`Are you sure you want to continue connecting (yes/no)? `
With the command `ssh-keyscan` get the key a Weblate ssh server and skip the previous question
> [FIX] apis.py: Adding new metod _ssh_keyscan to run the ssh-keyscan over the weblate-ssh server

- travis/apis.py
Change the regular expression to support domain containing '-' equal to `translation.odoo-community.org`
> [FIX] apis.py: Fix the regular expression to detect the domain containing '-'

- travis/travis_install_nightly
This PR is related with many false red because many projects don't have assigned the environment variable to install wkhtmltopdf patched version but the .travis.yml has `apt-get install wkhtmltopdf` so is failing because is not patched.
We can change all OCA projects to assign the environment varibable correctly but we can avoid many false red detecting if currently is installed then overwrite it.
What do you think about?
cc @Yajo @lasley @gurneyalex @sylvain-garancher
> [REF] travis_install: Overwrite wkhtmltopdf if is installed

- .travis.yml
- tests/test_repo/broken_lint/case_fields.py
- tests/test_repo/broken_module/model.py
- tests/test_repo/broken_no_access_rule/dummy_model.py
- tests/test_repo/broken_uninstallable/model.py
- tests/test_repo/test_module/dummy_model.py
- travis/getaddons.py
- travis/git_run.py
- travis/run_pylint.py
- travis/self_tests
- travis/test_pylint
- travis/test_server.py
- travis/travis_transifex.py
- travis/travis_weblate.py
[REF] MQT: Migration to python3
- [REF] remove relative import and reduce expected lint errors
- [REF] py3: xmlrpclib compatilibity
- [FIX] test_server: Write bytes for binary file and print string
- [REF] Use br for regex
[REF] MQT: Compatibility with new api odoo
- [REF] compatible with old and new api
- [REF] remove deprecated _columns
- [REF] .travis.yml: Remove 6.1 and 7.0 odoo test since that 11 version don't support _columns and 6.1 and 7.0 just suppport _columns
[REF] .travis.yml: Enable py3 environment
> [REF] MQT: Migration to python3

- tests/test_repo/broken_module/__init__.py
- tests/test_repo/broken_module/interpreter_wox.py
- tests/test_repo/broken_uninstallable/__init__.py
- tests/test_repo/broken_uninstallable/interpreter_wox.py
- travis/clone_oca_dependencies
`clone_oca_dependencies` is breaking some things for me due to the shebang being to a direct python. 
Went ahead and changed all of the instances of `#!/usr/bin/python` to `#!/usr/bin/env python`
> [FIX] Fix Python shebangs to use env

- sample_files/.gitlab-ci.yml
> [ADD] gitlab: Add example to use gitlab

- travis/odoo_connection.py
- travis/travis_transifex.py
Bringing @yelizariev's changes suggested in https://github.com/OCA/maintainer-quality-tools/commit/27792ba2e1e95212c1a0670784bdd3cd1a5b33c0#commitcomment-25074733 for making Travis work again, as Weblate has been delayed as there are still problems for having the same features.
This also solves linter problems with `import sentences not at the top level`
cc @Tecnativa @moylop260 @dreispt
> [MIG] port transifex to P3 + support odoo 11.0

- sample_files/.travis.yml
* Note about how to install SASS manually in Travis file is deprecated with `WEBSITE_REPO="1"`
> [FIX] Remove deprecated SASS note

- requirements.txt
- travis/test_server.py
Fix the error `No module named configparser` for py2 instances where is not installed the package `configparser`
> [FIX] test_server: Use configparser py2 and py3 compatibility

- travis/cfg/travis_run_pylint_beta.cfg
- travis/cfg/travis_run_pylint_pr.cfg
Enable the `unnecessary-utf8-coding-comment` check for beta and pr configuration
> [REF] travis/cfg: Enable the unnecessary-utf8-coding-comment check for beta and pr configuration

- travis/clone_oca_dependencies
I was messing around in LasLabs/docker-odoo#1 & realized that an easy way for us to get a pretty good speed boost on our builds is to use Github archives instead of cloning the repo.
Is there a specific reason we are cloning here? Are these archives not always current or something? I tested a bit and they seem to be current.
I'm not proposing this code in its current form, but something very close. Any thoughts?
> [IMP] Switch git clone for archive download in depends download

- travis/test_flake8
Before this patch, you only can flake8 all code under $PWD. Now you can call it against any unrelated list of folders, mirroring what you can also do with pylint.
@Tecnativa
> [IMP] Support $INCLUDE_LINT for flake8 too

- sample_files/.gitignore
- travis/cfg/travis_run_pylint_beta.cfg
- travis/run_pylint.py
By converting the beta file into a real pylint-odoo cfg file, other CI tools that allow a "failed but passing" status, such as Gitlab CI, can use pylint-odoo directly with this file without all the extra travis-specific complexity of MQT.
@Tecnativa
> [IMP] Allow using pylint beta cfg file in standalone mode

- .travis.yml
- travis/self_tests
[FIX] .travis.yml: Fix false red for stable branches, forcing PR flag
[FIX] self_tests: Returns exit code with the result of the tests
Currently there is a error with the dictionary expected but is not visible because show a false green.
Other issue is that the travis result of the branch stable is red because the flag of PR was off.
> [FIX] tests: Update dictionary of expected errors.

- travis/run_pylint.py
This PR fixes:
Traceback (most recent call last):
File "/home/travis/maintainer-quality-tools/travis/test_pylint", line 59, in <module>
result = run_pylint.pylint_run(is_pull_request, version, git_work_dir)
File "/home/travis/maintainer-quality-tools/travis/run_pylint.py", line 170, in pylint_run
(key, value) for key, value in real_errors['by_msg'].items()
KeyError: 'by_msg'
It happens when you delete all modules in a repository, thus there aren't error messages because there is no module.
> [FIX][travis] 'by_msg' not in errors

- travis/travis_install_nightly
in v11, phonenumbers is an undeclard optional dependency. Not having this
module will trigger a warning in the logs and then a failed runbot
build.
> [FIX] runbot builds on 11.0

- sample_files/.gitignore
- travis/run_pylint.py
First of all, in PR https://github.com/OCA/maintainer-quality-tools/pull/518 I forgot to the remove the **repeated** `.vcode` put by @Yajo in PR https://github.com/OCA/maintainer-quality-tools/pull/519.
And secondly, in PR https://github.com/OCA/maintainer-quality-tools/pull/526 I forgot to check the `get_count_fails` method that also uses `'by_msg'` key.
I hope I don't forget anything else  :grimacing:
> [FIX][travis] 'by_msg' key & .gitignore

- travis/run_pylint.py
- travis/test_pylint
in order to get the version autodetection the docs claim at the end of https://github.com/hbrunn/maintainer-quality-tools/blob/be6e4222c98128950c61bfad1b1ec64706f86a44/git/README.md, we need to pass an empty string to https://github.com/hbrunn/maintainer-quality-tools/blob/be6e4222c98128950c61bfad1b1ec64706f86a44/travis/run_pylint.py#L124
I don't really see the point of checking against the empty string there, maybe we should just check for falsyness?
> [FIX] adapt behavior to docs

- travis/travis_install_nightly
* Advantages using git clone instead of the tar file:
- Running MQT script from your local machine or docker you can re-use the odoo repository to upgrade it (`git pull`)
- Using `git depth=50` like as travis-ci uses we will have a faster download.
- We can know the odoo sha of the build if there is an error you can reproduce it using the same sha.
- We can verify a custom change applied to odoo repository if there is a `sed` executed or `patch` using `git diff` and return to original state.
- Remove flaky error using tar files:
- https://github.com/OCA/maintainer-quality-tools/issues/539
- We can use a odoo's PR to test it
More info about: 
https://github.com/OCA/maintainer-quality-tools/issues/539#issuecomment-381648037
- Waiting green result https://github.com/OCA/l10n-spain/pull/829
> [REF] install: Use git instead of tar to download odoo

- sample_files/.travis.yml
* By default postgresql-9.1 is installed but there is issue related:
- https://github.com/OCA/maintainer-quality-tools/issues/432#issuecomment-281580935
* Better use higher PostgreSQL version
Continuation from https://github.com/OCA/maintainer-quality-tools/pull/538
> [REF] sample_files: .travis.yml - Higher postgresql version

- cfg/.coveragerc
When using MQT outside of travis the hardcoded /build/ dir of Travis is causing an issue by looking in the wrong place.
This offers a more flexible way to check the code that needs to be tested because even in gitlab we can define the TRAVIS_BUILD_DIR.
Downside is that if someone places other pieces of code in the /build/ dir next to the project they will be ignored (if that was ever the plan).
A better way would be to use a separate env var and handle default values but that might introduce new dependencies (such as envsusbt and such)
Close https://github.com/OCA/l10n-spain/pull/848
> Using TRAVIS_BUILD_DIR variable instead of hardcoded path

- travis/cfg/travis_run_flake8.cfg
- travis/cfg/travis_run_flake8__init__.cfg
this makes the flake8 call ignore files in the examples directory as pylint-odoo does. Fixes OCA/pylint-odoo#193
> [ADD] exclude examples directory

- travis/cfg/travis_run_pylint_exclude_61.cfg
- travis/cfg/travis_run_pylint_exclude_70.cfg
- travis/cfg/travis_run_pylint_pr.cfg
- travis/odoo_connection.py
- travis/run_pylint.py
- travis/test_pylint
- travis/test_server.py
- travis/travis_install_nightly
- travis/travis_weblate.py
This applies some minor fixes to comments and strings all over the
project, including typos, grammatical errors, etc.
For instance:
- It don't -> it doesn't
- A Odoo server -> An Odoo server
- You need add a new conventions -> You need to add new conventions
> [FIX] *: Fix typos and grammatical errors

- travis/travis_install_nightly
More info about: https://github.com/odoo/odoo/issues/25632
Note: It is not a good idea pinned the version but currently we will have all our runbot's instances without connection
UPDATED:
You can see an example of the error connecting a recent build from our runbot:
- https://runbot.odoo-community.org/runbot/226/11.0
> [FIX] install: Use compatible less version for odoo

- sample_files/.gitlab-ci-2.yml
This is, imho, a cleaner gitlab ci example.
Uses the docker python 3.5 image with an extra service dependency on the postgresql image. 
Testing can be done on the public shared gitlab runners, or private runners when needed.
An example where a public oca repository is tested can be found https://gitlab.com/road-support/oca-account-invoicing/
(It's currently failing because the codecoverage has gone down, test and lint check are green)
> [UPD] Cleanup gitlab-ci file using python-3.5 image

- travis/self_tests
In a recent change on pylint-odoo [1], it was introduced a fix to
recognize a badly-formatted version in manifest, which now depends on
the Odoo version. When the version is provided and it's a numeric
version value (e.g. not "master") it's taken into account to determine
whether the version defined in the manifest is formatted correctly.
Since versions in tested modules are as follows:
- Two set to 8.0
- Four set to wrong values (e.g. 1.0)
When the version is numeric but it's not 8.0, there will be six errors,
otherwise there will be four. In these tests, the only case when it's
numeric but it's not 8.0, is when testing 7.0.
[1] Pylint change: https://github.com/OCA/pylint-odoo/commit/6b1f1e1bfaf
> [FIX] self_tests: Adjust expected values after pylint change

- travis/travis_install_nightly
Currently, only those versions of wkhtmltopdf that come on a .tar.xz are
installable, but not those who come on .deb packages. That includes the
most recent version 0.12.5.
This commit adds support for those versions, which includes 0.12.1 and
0.12.5
Closes #572
Dummy PR: https://github.com/OCA/server-tools/pull/1371
> [IMP] travis_install_nightly: support wkhtmltopdf 0.12.5

- .travis.yml
- requirements.txt
Fix the following warning:
- websocket-client module is not installed
More info about:
https://github.com/OCA/e-commerce/pull/250
https://travis-ci.org/OCA/e-commerce/jobs/436197303#L1456
Add 12.0 environment in order to detect this kind of errors early.
> [REF] requirements: Supports new frontend unittest engine

- travis/run_pylint.py
while executing it was giving error in local before commit because of the white space from the repo itself.
flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8.cfg
./.git/hooks/run_pylint.py:131:14: E211 whitespace before '('
./.git/hooks/run_pylint.py:164:10: E211 whitespace before '('
./.git/hooks/run_pylint.py:174:10: E211 whitespace before '('
./.git/hooks/run_pylint.py:195:18: E211 whitespace before '('
> remove whitespace before ( for E211

- travis/test_server.py
in https://github.com/Therp/Therp-Addons, I have a [test](https://github.com/Therp/Therp-Addons/blob/10.0/fetchmail_inbox/tests/test_fetchmail_inbox.py#L18) that calls `mail.thread#message_process` with Odoo's [test mails](https://github.com/OCA/OCB/blob/10.0/addons/mail/tests/test_mail_gateway.py#L70) from the mail module. Note those contain non-ascii characters, and the mail module logs the sender.
I spent today to debug the fact that this test never finishes, actually, the build just dies as in https://travis-ci.org/Therp/Therp-Addons/jobs/482456801#L1271 - after quite some questioning my sanity, I understood this is neither Odoo breaking nor the test, but the test script itself. This should never happen in my opinion, whatever garbage Odoo logs, we need to be able to deal with it. …
> [FIX] never break for decoding errors in log

- travis/run_pylint.py
- travis/test_flake8
With this MR we will be able to use the environment variable `EXCLUDE_FLAKE8` to specify modules to be excluded from the flake8 checks.
Use case: sometimes we need to ignore the warnings for some modules because they are from a third party and we don't/can't maintain them.
Example:
Here we are getting a lot of warnings from some third party modules, but we can skip them like this:
And then we see the warnings for the modules that correspond to us to maintain, and our CI tests don't display the false alarms.
> [IMP] Alow excluding specified modules from test_flake8 using env var

- requirements.txt
Same as https://github.com/odoo/odoo/commit/8bda4744b5a2d6faa5e6900bdbaade460b7e1a6b.
This PR tries to greenify the maintainer-quality-tools repo. The broken analysis are:
> [FIX] requirements: improve python3 compatibility

- requirements.txt
- travis/cfg/travis_run_pylint.cfg
- travis/cfg/travis_run_pylint_beta.cfg
- travis/cfg/travis_run_pylint_exclude_61.cfg
- travis/cfg/travis_run_pylint_exclude_70.cfg
It happens that `travis/git_run.py` and `travis/test_server.p`y use `six` library, but that library is not in `requirements.txt` file. Thus, this PR fixes that.
Also, as a bonus, I updated the disable message commented sections.
> [FIX] Include six in requirements.txt

- travis/cfg/travis_run_flake8.cfg
E203 is not PEP 8 compliant, we should tell Flake8 to ignore these warnings. https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements
This change allows us to use MQT on code formatted by black and thus opens the door to the use of this tool on OCA repositories.
> [REF] travis_run_flake8.cfg: disable E203 whitespace before ':'

- travis/test_server.py
- travis/travis_run_tests
This is mainly to let the bot bump the version number after the .pot as been updated.
Two commits for easier review: the first is just cosmetics.
> Run makepot on merge bot branches too

- travis/travis_install_nightly
Related with:
- https://github.com/eslint/eslint/blob/master/docs/user-guide/migrating-to-6.0.0.md#drop-node-6
- https://github.com/eslint/eslint/issues/11456
PR related with pylint-odoo: https://github.com/OCA/pylint-odoo/pull/248
> [FIX] pylint: javascript-lint are disable because of requires upgrade nvm

- sample_files/oca_dependencies.txt
- travis/clone_oca_dependencies
This improvement allows to clone repositories selecting a commit SHA.
Useful when you want to work with an specific state of the repository
that is not marked by any branch.
The syntax of the line you have to place in `oca_dependencies.txt` is as
follows:
```
server-tools git@github.com:OCA/server-tools.git 12.0 0c2c386
```
Note that you need to explicitly indicate a branch where the commit is
present because git doesn't allows to clone or fetch using directly a
commit SHA without having a configuration parameter set at server side[1].
So, when you choose to clone a repository using a commit SHA,
`clone_oca_dependencies` will fetch the commit history of the branch
you selected and then reset `HEAD` position to that commit.
[1] https://stackoverflow.com/questions/31278902/how-to-shallow-clo …
> [IMP] clone_oca_dependencies: Clone repositories from commits SHA

- sample_files/pre-commit-13.0/.eslintrc.yml
- Sort file alphabetically to make maintenance easier
- Remove more rules disabled in https://github.com/prettier/eslint-config-prettier/blob/v6.9.0/index.js
- Remove `false` and put `readonly` in globals; [`false` is deprecated](https://eslint.org/docs/user-guide/configuring#specifying-globals)
- All failures were tagged as warn because until today, pylint-odoo only printed warnings in JS files. IMHO it's time to flip the switch, so I manually enabled some checks as errors.
@Tecnativa TT20357
> Update eslintrc configuration

- sample_files/.travis.yml
After https://github.com/OCA/maintainer-quality-tools/pull/630, some linters like eslint may produce warnings that would be unnoticed if no errors were found.
To be able to still see the warnings, I add `--verbose` to pre-commit.
Also, I add the handful `--color always` to make colored output even without a TTy, as it was the case.
@Tecnativa TT20357
> [IMP] Use verbose colored pre-commit in CI

- .travis.yml
- sample_files/.gitlab-ci-2.yml
- travis/travis_install_nightly
Related with https://github.com/OCA/maintainer-quality-tools/issues/626
cc @Yajo 
And Supporting broken_uninstallable module
After new logger.error from https://github.com/odoo/odoo/commit/c5d6a39
> [REF] install: pin coveralls version and supporting broken_uninstallable module

- .travis.yml
Since that https://docs.travis-ci.com/user/languages/python/#specifying-python-versions is updated to use 3.7
> [REF] .travis.yml: Using py3.7 stable instead of dev

- sample_files/pre-commit-13.0/.pre-commit-config.yaml
- sample_files/pre-commit-13.0/.prettierrc.yml
> Let prettier indent XML files

- travis/travis_install_nightly
Setting a `MQT_DEP=PIP` environment variable in `.travis.yml` instructs MQT to discover and install addon dependencies using pip instead of `oca_dependencies.txt` and `requirements.txt`.
Specific test requirements such as specific branches of dependencies can be installed by creating a `test-requirements.txt` file at the repo root.
This is a new, opt-in, version of #343.
Example: https://travis-ci.org/github/acsone/mis-builder/jobs/661629796
> Add opt-in mechanism to install dependencies with pip

- travis/test_server.py
- travis/travis_makepot
We don't need an `addons_path` when addons are installed with pip,
and if we have the same addon in several places in the `addons_path`, this confuse
.pot file generation.
Follow-up from #646
> [FIX] do not set addons_path when installing with pip

- travis/travis_install_nightly
When providing a list of editable installs, it is important
to give pip a cue about the name of packages being installed
(#egg=) so it knows which one will be editable and it will
not attempt to fetch them from indexes as dependencies.
Side note: we want them editable so coverage picks-up the source code.
> give package name cue to pip install

- travis/travis_install_nightly
It confuses runbot (or is it travis2docker?).
It is not needed in this specific case because odoo is installed
with -e too and comes first in sys.path so it's `__init__.py` is imported first.
> do not install odoo-autodiscover in MQT_DEP=PIP mode

- requirements.txt
Since these are unused yet installed in all builds, let's save some travis cycles.
> remove unused transifex requirements

- .travis.yml
- README.md
- requirements.txt
- sample_files/.gitlab-ci-2.yml
- travis/travis_after_tests_success
- travis/travis_install_nightly
As recommended by https://docs.coveralls.io/python
fixes #642
> Remove coverall suport, install codecov in travis_after_test_success

- requirements.txt
- travis/test_server.py
use py2/py3 compatible code
`configparser` is the only dependency that was needed in addition to regular Odoo dependencies in order to run `test_server.py`. Removing it makes it possible to avoid MQT's `requirements.txt` in most cases.
> remove dependency on configparser

- travis/travis_install_nightly
- Move some installations steps into MQT_DEP=OCA code path (no behaviour change in that mode).
- Do not install mqt's `requirements.txt` in MQT_DEP=PIP mode.
- Generate potentially missing `setup.py` files in MQT_DEP=PIP mode.
> install less dependencies in MQT_DEP=PIP mode

- travis/travis_install_nightly
This should re-enable tours everywhere where PIP mode is being used and tours are being skipped.
See https://github.com/OCA/social/pull/560#issuecomment-651704674 and https://github.com/OCA/social/pull/555#issuecomment-651687647.
@sbidoul @Tecnativa TT24523
> Install MQT dependencies in PIP mode too

- travis/travis_install_nightly
Do not fail if there is no addon to test.
> In pip install mode, support empty addons list

- travis/travis_install_nightly
`test-requirements.txt` was used only for `MQT_DEP=PIP` mode.
There's no good reason to not use it for `MQT_DEP=OCA`.
This helps keeping the same format across repositories 
and finally separate functional dependencies from test ones.
> travis_install_nightly: use test-requirements always

- travis/travis_install_nightly
Use a package index that redirects to the OCA wheelhouse for Odoo addons,
and to pypi.org for all other packages. This is to make sure we don't
inadvertently accept non-OCA addons in dependencies.
This index is made using [simpleindex](https://pypi.org/project/simpleindex/) with the following configuration:
```
[routes."oca-simple-and-pypi/odoo{series}-addon-{addon}"]
source = "http"
to = "https://wheelhouse.odoo-community.org/oca-simple/odoo{series}-addon-{addon}/"
[routes."oca-simple-and-pypi/{project}"]
source = "http"
to = "https://pypi.org/simple/{project}/"
[server]
host = ...
port = ...
```
> Use our own package index

- travis/travis_install_nightly
Using a fresh setuptools helps in some case, as it obey python-requires properly, and more and more packages have recent releases that require python >= 3 and must be avoided for python 2.
> Upgrade setuptools

- travis/travis_install_nightly
- 2to3 support has been [removed since setuptools 58.0.0](https://setuptools.readthedocs.io/en/latest/history.html#breaking-changes)
- some deps of odoo use it, e.g. [feedparser==5.2.1](https://github.com/odoo/odoo/blob/14.0/requirements.txt#L6): [`setup.py`](https://github.com/kurtmckee/feedparser/blob/5.2.1/setup.py#L6)
- as a consequence, travis builds will fail:
```
Collecting feedparser==5.2.1
Downloading feedparser-5.2.1.zip (1.2 MB)
ERROR: Command errored out with exit status 1:
command: /home/travis/virtualenv/python3.6.7/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tj513bvt/feedparser_2b08e92758ea44ac9203ddee5abb9821/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tj513bvt/feedparser_2b08e92758ea44ac9203ddee5abb9821/setup.py'"'"';f = …
```
> [FIX] avoid setuptools 58 that removed support for 2to3

- .travis.yml
- travis/run_pylint.py
Compatible with new way to get result of messages based on:
- https://github.com/PyCQA/pylint/commit/16c09cb48a3c66f453faccdf380aea6969d61202#diff-3a681c16a79ae9818f939e08df8b9bb92ef9ce6d5fc65c360d7c9b526c3c3410R507
> [FIX] pylint: Compatibility pylint<2.12

- travis/run_pylint.py
The following commit:
- https://github.com/OCA/maintainer-quality-tools/commit/365183598bc86889de0349aa23d015cc5f356577
It is compatible with new way to get result of messages based on:
- https://github.com/PyCQA/pylint/commit/16c09cb#diff-3a681c16a79ae9818f939e08df8b9bb92ef9ce6d5fc65c360d7c9b526c3c3410R507
However, new corner cases were raised
e.g. https://github.com/OCA/sale-workflow/pull/2004#issuecomment-1118506829
It is because the test_pylint script consider returns early using a dict
So, we need to transform new way object to old way dict in order to be compatible with this old script
with minimal changes since that new pylint checks are available from pre-commit
> [REF] run_pylint: Compatibility with pylint>2.12
