OCA/maintainer-quality-tools

travis/test_server

[FIX] append the whole log_record, not just its message

---

travis/test_server

I fooled myself several times by now by using UNIT_TEST="0" and expecting this turns off unit tests

[IMP] allow to exlicitly turn off UNIT_TEST

---

.travis.yml
sample_files/.travis.yml

see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
closes #170

set sudo: required to avoid container based builds

---

travis/requirements.txt

Reverts OCA/maintainer-quality-tools#161 as version 0.10.4 fixed this issue. cf odoo/odoo#5057

unfreeze werkzeug versions

---

.travis.yml
sample_files/.travis.yml
travis/travis_install_nightly

Allows use of container based builds which are a lot quicker to load
Closes  #175

Remove sudo requirements and use addon apt packages

---

travis/clone_oca_dependencies

Many people have issues testing MQT on their own forks due to this hardcoding

Unhardcode OCA

---

travis/test_server.py

More info here: https://github.com/OCA/maintainer-quality-tools/issues/176

[FIX] test_server: oca/mqt issue fix #176

---

.travis.yml
sample_files/.travis.yml

enables using travis container based infrastructure
for new projects
Also build MQT on travis container based infra while we are at it.

update sample .travis.yml file

---

sample_files/.travis.yml

thanks to @hbrunn for showing me how to do this

explain how to install wkhtmltopdf for travis tests

---

.travis.yml
tests/test_repo/broken_module/I0013.py
tests/test_repo/broken_module/ipdb.py
tests/test_repo/broken_module/model.py
tests/test_repo/broken_module/pdb.py
tests/test_repo/broken_module/pudb.py
travis/test_pylint

This PR depend of https://github.com/OCA/maintainer-quality-tools/pull/229
You can view the real changes of this PR in the last commit diff.

[IMP] test_pylint: Add feature to validate expected errors vs a environ variable

---

sample_files/README.md

Update repository README.md. Merge when

[IMP] gen_addons_table: add addons placeholder in README.md template

---

.travis.yml
travis/test_pylint

Fix next cases: https://github.com/OCA/maintainer-quality-tools/issues/245

[FIX] pylint: Fix VERSION environment variable empty case

---

sample_files/README.md

I found this short OCA description in several repos. It's good to have it in the template.

README.md template: add OCA footer

---

sample_files/README.md

Coveralls has changed the page and the badge links

[IMP] README: Update coveralls badge

---

travis/getaddons.py

Fix OCA/maintainer-quality-tools#277

[REF] getaddons: Fix 'unknown revision' error in get modules changed

---

git/README.md
git/getaddons.py
git/git_run.py
git/pre-commit
git/run_pylint.py
git/test_pylint
git/travis_helpers.py
travis/getaddons.py
travis/git_run.py
travis/self_tests
travis/test_pylint

- [REF] git-hook: Add compatibility for python script
- [REF] git-hook: Add install pylint-odoo plugin and version variable
- [REF] test_pylint: Add compatibility for git-hook.
- [REF] self_tests: Add git-hook tests

[REF] git-hook: py script compatibility

---

travis/cfg/travis_run_pylint_pr.cfg

Check if the module comes with screenshots to be displayed on Odoo Apps
Example: https://www.odoo.com/apps/modules/8.0/crm_voip/

[IMP] Add images to required keys of manifest file

---

.travis.yml
travis/test_server.py

- To run custom script from other sources. (by example: runbot with travis2docker)

[REF] test_server: Add method to run commands from environment variables

---

.travis.yml
tests/test_repo/broken_lint/case_deprecated.py
travis/cfg/travis_run_pylint_pr.cfg

@dreispt and @gurneyalex request from [twitter](https://twitter.com/reis_pt/status/699238110375366657?cn=bWVudGlvbg%3D%3D&refsrc=email)
- <img width="865" alt="screen shot 2016-02-15 at 12 24 24 pm" src="https://cloud.githubusercontent.com/assets/6644187/13057042/1cc99b98-d3df-11e5-8e10-e445bf8d02f9.png">
- https://travis-ci.org/OCA/maintainer-quality-tools/jobs/109412780#L471

[IMP] pylint_pr.cfg: Enable check eval-used - W0123

---

tests/test_repo/broken_module/__openerp__.py
travis/cfg/travis_run_pylint_pr.cfg

[IMP] pylint: Enable check to verify version format in manifest file

[IMP] pylint: Enable check to verify version format in manifest file

---

.travis.yml
travis/cfg/travis_run_pylint_beta.cfg
travis/cfg/travis_run_pylint_exclude_61.cfg
travis/cfg/travis_run_pylint_exclude_70.cfg
travis/cfg/travis_run_pylint_pr.cfg

- Add new checks from new version of [pylint-odoo-1.2.0](https://github.com/oca/pylint-odoo) just in modules changed, following the [roadmap](https://github.com/OCA/pylint-odoo/issues/14)

[REF] pylint.cfg: Enable new checks from pylint-odoo-1.2.0

---

travis/cfg/travis_run_pylint_beta.cfg
travis/cfg/travis_run_pylint_pr.cfg

- Enable the following new checks [PR-pylint-odoo-1.3.0](https://github.com/OCA/pylint-odoo/pulls?utf8=%E2%9C%93&q=is%3Apr+milestone%3A1.3.0+) - (Depends on merge all)
- Enabled just for modules changed and without affect travis build status

[REF] pylint.cfg: Enable new checks from pylint-odoo-1.3.0

---

requirements.txt
travis/clone_oca_dependencies
travis/travis_install_nightly

https://github.com/eliben/pycparser/issues/147

temp fix for pycparser issue

---

travis/test_server.py

Fix https://github.com/OCA/maintainer-quality-tools/issues/361

[FIX] test_server: Fix list concatenation with Null

---

cfg/.coveragerc

* Exclude guard for import error from coverage reports

[IMP] coveragerc: Exclude ImportError guard from coverage

---

sample_files/.travis.yml

Include instructions for installing sass command.

.travis.yml: sass install instructions

---

travis/travis_install_nightly

Help to fix projects where is required to test with webkit (wkhtmltopdf) patched.
https://github.com/OCA/reporting-engine/pull/86#issuecomment-265598246

[REF] travis_install_nightly: Install webkit patched

---

travis/test_server.py

- Avoid show database password or `db_*` parameters

[REF] test_server: Hidden secret params

---

travis/apis.py
travis/git_run.py
travis/odoo_connection.py
travis/test_server.py
travis/travis_run_tests
travis/travis_weblate.py

Attaching the script to update weblate using the github api
This script does:
- Weblate pull
- Update the .po based on the code
- Merges by prioritizing github changes
- Commits based using github's api
FOR MERGER
==========
Use merge and squash from github

[ADD] weblate: Add support for weblate translations

---

travis/travis_weblate.py

I ported the changes made in https://github.com/odoo/odoo/pull/17925 over the files `odoo/addons/base/ir/ir_translation.py` and `odoo/tools/translate.py`
Now MQT apply these patch if the patch has not been applied
The change in the file `(odoo|openerp)/addons/base/ir/ir_translation.py` 
The change in the file `(odoo|openerp)/tools/translate.py`

[FIX] travis_weblate.py: Adding more patch to de odoo

---

sample_files/.travis.yml

https://github.com/OCA/social/pull/179#issuecomment-314146715

[IMP] Add SASS & Compass install sample

---

sample_files/.travis.yml

I admittedly almost forgot this existed

[IMP] Add WKHTMLTOPDF_VERSION to Travis sample file

---

travis/test_server.py

For more info about see: 
- https://github.com/OCA/social/pull/179#issuecomment-316856790

[REF] test_server: Add db-filter to run phantomjs test well

---

travis/travis_install_nightly

Explicitly Source RVM to fix #471. Proof https://github.com/OCA/e-commerce/pull/194
cc @yajo

[FIX] Explicitly Source RVM to fix #471

---

travis/travis_install_nightly

* Source RVM from conditional paths (support T2D & Travis)
Testing in https://github.com/OCA/e-commerce/pull/194

[FIX] Only source rvm script if avail

---

travis/travis_install_nightly

In order to fix issues related with double versions of gem packages
Fix https://github.com/OCA/maintainer-quality-tools/issues/471

[FIX] install: Uninstall current gem packages

---

travis/travis_install_nightly

[FIX] travis_install_nightly: Freeze flake8 version

---

.travis.yml
tests/test_repo/broken_deprecated/__openerp__.py
travis/cfg/travis_run_pylint_pr.cfg

https://github.com/OCA/pylint-odoo/pull/165#issuecomment-339806489

[REF] disable license OEEL-1 for oca projects

---

.coveragerc
.travis.yml
travis/getaddons.py
travis/run_pylint.py
travis/self_tests
travis/test_pylint
travis/travis_install_nightly
travis/travis_run_tests

[REF] Use expected errors of pylint based on dictionaries instead of a global total value

---

travis/test_server.py

Fix https://github.com/OCA/maintainer-quality-tools/issues/508
Related with https://github.com/OCA/maintainer-quality-tools/issues/503
Dummy PR: https://github.com/OCA/OCB/pull/677

[REF] test_server: Use configparser for config files

---

travis/cfg/travis_run_pylint_pr.cfg
travis/run_pylint.py

This way we DRY the files and also allow the PR cfg file to be used in standalone mode.
@Tecnativa

[IMP] Remove pylint beta messages from PR cfg file

---

travis/travis_install_nightly

Reverts OCA/maintainer-quality-tools#527
After https://github.com/odoo/odoo/commit/b79d05fff0cacb4d99ebc1b60f44d8dab757b806

Revert "[FIX] runbot builds on 11.0"

---

travis/getaddons.py
travis/run_pylint.py
travis/self_tests
travis/test_server.py

Superseeds https://github.com/OCA/maintainer-quality-tools/pull/535.

[IMP] Allow to filter by applications or l10n modules 

---

sample_files/.travis.yml

see discussion in https://github.com/OCA/web/pull/909#issuecomment-380045633 and https://github.com/OCA/web/pull/889#issuecomment-379801321

[IMP] use higher python version, disable system site packages

---

travis/test_server.py
travis/travis_transifex.py

[FIX] Test_server: minor touches

---

travis/cfg/travis_run_flake8.cfg

More info about https://github.com/OCA/maintainer-quality-tools/issues/545

[REF] flake8.cfg: Allow W504 and W503 flake8 style

---

travis/test_server.py

This improves the error message, so it's clearer.

[IMP] test_server: Improve error msg when "Modules loaded." is not found

---

requirements.txt

This is used nowadays: https://github.com/OCA/maintainer-quality-tools/blob/4c2ca5f719c7c10fe35e15d4108da09ae60b51f6/travis/git_run.py#L4
@Tecnativa

[FIX] Add six dependency

---

.travis.yml
travis/git_run.py
travis/self_tests

Detecting early cases like:
- https://github.com/OCA/maintainer-quality-tools/issues/589

[REF] .travis.yml: Enable tests for lints using py3

---

.editorconfig

This symlink was broken.
@Tecnativa TT20357

Update .editorconfig symlink

---

sample_files/pre-commit-13.0/.isort.cfg
sample_files/pre-commit-13.0/.pre-commit-config.yaml

sample files: simpler isort configuration

---

sample_files/pre-commit-13.0/.pre-commit-config.yaml

This will ensure setup.py files are generated on pull requests and avoid one bot commit.

sample files: generate setup.py files in pre-commit

---

sample_files/pre-commit-13.0/.pre-commit-config.yaml

sample files: exclude rst from merge conflict detection

---

travis/clone_oca_dependencies
travis/travis_install_nightly

This came from https://github.com/OCA/maintainer-quality-tools/pull/355
and is now resolved upstream.

revert pycparser temporary fix

---

README.md

@sbidoul You were took quick on the trigger 😃 
Following #657, here are additional improvements on the README.

[IMP] README: improve pre-commit instructions

---

travis/travis_install_nightly

This may fix our runbot issues.

Avoid setuptools 50

---

travis/cfg/travis_run_pylint.cfg

More info about:
- https://github.com/OCA/maintainer-quality-tools/issues/679
- https://github.com/OCA/pylint-odoo/issues/199

[REF] travis.cfg: Enable development-status-allowed check

---

travis/travis_makepot

Use a personal access token to push to github

---

travis/test_server.py
travis/travis_run_tests

[UPD] makepot: add 14.0 and 15.0 support
